{{- if .Values.app.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "juice-shop.fullname" . }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "juice-shop.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  ingressClassName: {{ .Values.app.ingress.className | default "nginx" }}
  rules:
    - host: {{.Values.app.ingress.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "juice-shop.fullname" . }}
                port:
                  number: {{.Values.service.port}}
  {{- if .Values.app.ingress.tls }}
  tls:
    {{- toYaml .Values.app.ingress.tls | nindent 4  }}
  {{- end }}
{{- end }}