apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "juice-shop.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "juice-shop.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ include "juice-shop.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "juice-shop.fullname" . }}
    spec:
      serviceAccountName: {{ include "juice-shop.serviceAccountName" . }}
      containers:
        - name: {{ include "juice-shop.fullname" . }}
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          ports:
            - containerPort: {{.Values.service.port}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1